kind: Service
apiVersion: v1
metadata:
  name: prophet
spec:
  type: NodePort
  selector:
    app: prophet
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prophet-deployment
  labels:
    app: prophet
spec:
  replicas: 1
  strategy: 
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: prophet
  template:
    metadata:
      labels:
        app: prophet
    spec:
      serviceAccountName: default
      containers:
      - name: prophet-container
        image: gcr.io/mooc-hub/prophet
        env:
        - name: secret_key
          value: "IHaWZnwE8SobnIAe27x8y+0y0iWIkzW9TVwD08hvPT4="
        resources:
          limits:
            memory: "6Gb"
        ports:
        - containerPort: 5000